# Jekyll
exclude: []
markdown: kramdown

permalink: /blog/:year/:month/:day/:title/
tagline: Mark Schabacker

navigation:
- text: Home
  url: /
  alt_url: /index.html
  layout: default
- text: Archive
  url: /blog/
  alt_url: /blog/index.html
  layout: archive

kramdown:
  input: GFM
  syntax_highlighter: rouge
