# Jekyll
exclude: []
markdown: redcarpet

permalink: /blog/:year/:month/:day/:title/
tagline: Mark Schabacker

navigation:
- text: Home
  url: /
  alt_url: /index.html
  layout: default
- text: Archive
  url: /blog/
  alt_url: /blog/index.html
  layout: archive
